Move vpgl_lvcs destructor to cxx file
vpgl_lvcs is derived from vbl_ref_count, thus destructor is implictly virtual.
As destructor is the only virtual function in vpgl_lvcs, DO NOT define inline;
destructor is the "key function" (first non-inline, non-pure, virtual function).

Defining in cxx protects against "undefined reference to vtable" linking errors.
https://gcc.gnu.org/wiki/VerboseDiagnostics#missing_vtable