BUG:  jpeg_boolean not convertable to C++ bool
vxl/core/vil/file_formats/vil_jpeg_compressor.cxx:76:5: error: no matching function for call to 'jpeg_start_compress'
    jpeg_start_compress (&jobj, write_all_tables);
    ^~~~~~~~~~~~~~~~~~~
<..>/include/jpeglib.h:1010:14: note: candidate function not viable: no known conversion from 'bool' to 'jpeg_boolean' for 2nd argument
EXTERN(void) jpeg_start_compress JPP((j_compress_ptr cinfo,
             ^