COMP: Missing header for std::numeric_limits<>
Clang 13 has fewer implied header includes.

The tests must explicitly include <limits> for the
numeric_limits definitions to avoid pre-processor errors like:

error: no member named 'numeric_limits' in namespace 'std'