Revert "COMP: Some compilers need both string.h & strings.h"
This reverts commit 901b41bb412ec18e12a7801a331a19e877b55ba3.

This resolves issue #734 of compilation failure, but
re-introduces a compiler warning about implicitly defined
function on some compilers.

Additional changes to use

v3p/geotiff/cpl_serv.h:104:36: warning: implicit declaration of function ‘strcasecmp’ [-Wimplicit-function-declaration]