BUG: VXL_CONSTEXPR requires initialization
vxl/core/vnl/vnl_numeric_traits.h:182:41: error: constexpr static data member ‘maxval’ must have an initializer
   static VNL_EXPORT VXL_CONSTEXPR short maxval; // = 0x7fff;