BUG: Address missing shared_ptr for VS9
This patch addresses the following compilation error:

vxl\vcl\vcl_compiler.h(940): fatal error C1189: #error :  "Missing
definition for SHARED_PTR"

Older Visual Studio have tr1 include not in a tr1 directory but still
in the tr1 namespace, this patch add support for this configuration.