COMP: Do not do __errno_location workaround on Android.
This patch was integrated from a change made in ITK:
commit 7251f76aee7a4bad07d0b2ac2485b0976c045959
Author: Matt McCormick <matt.mccormick@kitware.com>
Date:   Sat Jan 31 15:41:48 2015

    COMP: Do not do __errno_location workaround on Android.

    /home/matt/src/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_cerrno.h: In function 'int* __errno_location__Fv()':
    /home/matt/src/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_cerrno.h:16:73: error: '__errno_location' was not declared in this scope
     extern "C" inline int* __errno_location__Fv() { return __errno_location(); }
                                                                             ^
    /home/matt/src/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_cerrno.h: In function 'int* _Z16__errno_locationv()':
    /home/matt/src/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_cerrno.h:17:74: error: '__errno_location' was not declared in this scope
     extern "C" inline int* _Z16__errno_locationv() { return __errno_location(); }

    Change-Id: I4564adcdba883044161edcc989b6cfb98c253bc2