COMP: Allow compile with CMAKE_CXX_STANDARD=20
Fix two errors arisen from C++20 (related to the introduction of operator <=>)

First error:
`vnl_rational.h:457:71: warning: in C++20 this comparison calls the
current function recursively with reversed arguments`

```
[674/2452] Building CXX object core/vnl/CMakeFiles/vnl.dir/Templates/vnl_matrix+vnl_rational-.cxx.o
In file included from core/vnl/Templates/vnl_matrix+vnl_rational-.cxx:1:
core/vnl/vnl_rational.h: In instantiation of ‘bool operator==(T, const vnl_rational&) [with T = int; SFINAE = void]’:
core/vnl/vnl_matrix.hxx:801:14:   required from ‘vnl_matrix<T>& vnl_matrix<T>::normalize_rows() [with T = vnl_rational]’
core/vnl/Templates/vnl_matrix+vnl_rational-.cxx:4:1:   required from here
core/vnl/vnl_rational.h:457:71: warning: in C++20 this comparison calls the current function recursively with reversed arguments
  457 | inline bool operator==(const T r1, vnl_rational const& r2) { return r2==r1; }
```

Solved changing `r2==r1` to `r2.operator==(r1)`

Second error: `ambiguous overload for ‘operator==’`

```
In file included from core/vnl/tests/test_matrix_fixed_ref.cxx:5:
core/vnl/tests/test_matrix_fixed_ref.cxx: In function ‘void test_matrix_fixed_ref()’:
core/testlib/testlib_test.h:63:27: error: ambiguous overload for ‘operator==’ (operand types are ‘mfr’ {aka ‘vnl_matrix_fixed_ref<double, 3, 4>’} and ‘mf’ {aka ‘vnl_matrix_fixed<double, 3, 4>’})
   63 |   testlib_test_perform((p)==(v)); \
      |                        ~~~^~~~~
core/vnl/tests/test_matrix_fixed_ref.cxx:130:5: note: in expansion of macro ‘TEST’
  130 |     TEST("assign_const_ref", ref, other); // mfr vs mf
      |     ^~~~
In file included from core/vnl/tests/test_matrix_fixed_ref.cxx:3:
core/vnl/vnl_matrix_fixed.h:725:8: note: candidate: ‘bool vnl_matrix_fixed<T, num_rows, num_cols>::operator==(const vnl_matrix<T>&) const [with T = double; unsigned int num_rows = 3; unsigned int num_cols = 4]’ (reversed)
  725 |   bool operator==(vnl_matrix<T> const &that) const { return  this->operator_eq(that); }
      |        ^~~~~~~~
In file included from core/vnl/tests/test_matrix_fixed_ref.cxx:4:
core/vnl/vnl_matrix_fixed_ref.h:759:8: note: candidate: ‘bool vnl_matrix_fixed_ref<T, num_rows, num_cols>::operator==(const vnl_matrix_fixed_ref_const<T, num_rows, num_cols>&) const [with T = double; unsigned int num_rows = 3; unsigned int num_cols = 4]’
  759 |   bool operator==(vnl_matrix_fixed_ref_const<T,num_rows,num_cols> const &that) const { return  this->operator_eq(that); }
```

Solved adding a explicit operator== with a `vnl_matrix_fixed` argument.

All tests pass, configured with:

```
cmake ../src -DCMAKE_CXX_STANDARD=20
```