COMP: Missing cstdint header include
vxl/core/vnl/vnl_matlab_print_scalar.cxx:339:35: note: ‘SIZE_MAX’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
vxl/core/vnl/vnl_matlab_print_scalar.cxx: In function ‘void vnl_matlab_print_scalar(std::complex<long double>, char*, vnl_matlab_print_format)’:
vxl/core/vnl/vnl_matlab_print_scalar.cxx:352:35: error: ‘SIZE_MAX’ was not declared in this scope
  352 |   vnl_matlab_print_scalar(v, buf, SIZE_MAX, format);
      |                                   ^~~~~~~~

Identified as error with gcc13 compiler.