COMP: vnl_math perfect forward return type
This addresses errors such as:

  ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_math.h:159:5: error: 'auto'
  not allowed in function return type

With C++11 and ITK_WRAP_PYTHON=1 on macOS.

As discussed here:

   http://stackoverflow.com/questions/9864125/c11-how-to-alias-a-function

`using` is preferred when the names are the same. Do explicit perfect
forwarding for cuberoot since the name changed.