COMP: Remove test for MIPSPro support by cmake
vcl/tests/test_preprocessor.cxx:37:11: error:
'VXL_COMPILER_IS_MIPSpro' was not declared in this scope

Code removed for MIPSpro by cmake commit 214fcefa (Remove now-unused code
once used for MIPSpro on IRIX, 2019-02-21) actually changed a
public-facing API by dropping the `<prefix>_COMPILER_IS_MIPSpro`
definition from the generated compiler detection header.  CMake susequently
restored the definition hard-coded to `0` since the compiler will never
be MIPSpro.

As the MIPSpro compiler value will always be 0, we can safely remove it
from the vxl test.